version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-test-deploy:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circleci

      - heroku/deploy-via-git:
          requires:
            - node/run
          app-name: "ci-cd-iw1"
          filters:
            branches:
              only:
                - circleci
